import type { Metadata } from "next";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import TaskProvider from "@/contexts/TaskContext";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Todo-List App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TaskProvider>
      <html lang="fr">
        <body suppressHydrationWarning className={`antialiased`}>
          {children}
          <ToastContainer />
        </body>
      </html>
    </TaskProvider>
  );
}
